language: node_js

  #### Build app with docker #####
sudo: required  
services: 
  - docker
before_install:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl && sudo mv ./kubectl /usr/local/bin/kubectl   
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
  - docker build -t dotunn/travis:node0 .
  - docker images
  - sed -i -e 's|KUBERNETES_CLUSTER_CERTIFICATE|'"${KUBERNETES_CLUSTER_CERTIFICATE}"'|g' kubeconfig
  - sed -i -e 's|KUBERNETES_SERVER|'"${KUBERNETES_SERVER}"'|g' kubeconfig
  - sed -i -e 's|KUBE_ADMIN_CERT|'"${KUBE_ADMIN_CERT}"'|g' kubeconfig
  - sed -i -e 's|KUBE_ADMIN_KEY|'"${KUBE_ADMIN_KEY}"'|g' kubeconfig
  - sed -i -e 's|KUBERNETES_TOKEN|'"${KUBERNETES_TOKEN}"'|g' kubeconfig
  - cat $TRAVIS_BUILD_DIR 
script:
  - docker push dotunn/travis:node0
  - bash scripts/updateKube.sh

deploy:
  #########################
  # Deploy to AKS
  ######################### 
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: travis-node 


#notifications:
#  email:
#    recipients:
#      - stevedot.olabode@gmail.com # email associated with repo
#    on_success: always # can change to never
#    on_failure: always # can change to never