language: node_js
#### Build app with npm"
# node_js:
  # - 8
 
before_script:
  # - npm install (install all build dependencies on each line)
  # - npm install ........

# Unit testing
  - npm test


  #### Build app with docker #####
sudo: required  
services: 
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
  - docker build -t dotunn/travis:node travisci/node/
  - docker images
script:
  - docker push dotunn/travis:node

# deploy:
####### Deploy to aws codedeploy ######
# other supported providers can  be found here https://docs.travis-ci.com/user/deployment-v2/ 
 
  # - provider: codedeploy 
    # access_key_id: <encrypted access_key_id>
    # secret_access_key: <encrypted secret_access_key>
    # bucket: <bucket>
    # key: <bucket_key>
    # application: <app>
    # deployment_group: <deployment_group>
    # edge: true # opt in to dpl v2
# 
# notifications:
  # email:
    # recipients:
      # - stevedot.olabode@gmail.com # email associated with repo
    # on_success: always # can change to never
    # on_failure: always # can change to never