language: python
#### Build app with pip"
# python:
  # - 2.x
 
# before_script:
  # - "pip install --editable" 

  #### Unit Test ####
  # - "pip install pytest"
  # - pytest

# script:
  # - flask run --host 0.0.0.0

  #### Build app with docker image ####
services: 
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
  - docker build -t dotunn/travis:py .
  - docker images
script:
  - docker push dotunn/travis:py


# deploy:
# ####### Deploy to aws codedeploy ######
# # other supported providers can  be found here https://docs.travis-ci.com/user/deployment-v2/ 
#   - provider: codedeploy 
#     access_key_id: <encrypted access_key_id>
#     secret_access_key: <encrypted secret_access_key>
#     bucket: <bucket>
#     key: <bucket_key>
#     application: <app>
#     deployment_group: <deployment_group>
#     edge: true # opt in to dpl v2

notifications:
  email:
    recipients:
      - stevedot.olabode@gmail.com # email associated with repo
    on_success: always # can change to never
    on_failure: always # can change to never